export const USER_SIGN_IN = "USER_SIGN_IN"
export const ADD_PHONE= "ADD_PHONE"
export const ADD_PHONE_TO_CART= "ADD_PHONE_TO_CART"
export const DELETE_PHONE_FROM_CART = "DELETE_PHONE_FROM_CART"
export const QUANTITY_UPDATE = "QUANTITY_UPDATE"
export const USER_SIGN_OUT = "USER_SIGN_OUT"
export const GALLERY_DISLIKE_LIKE = "GALLERY_DISLIKE_LIKE"
export const GALLERY_COMMENT = "GALLERY_COMMENT"




